repos:
  # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/timothycrosley/isort
    rev: 5.2.2
    hooks:
      - id: isort
        name: Sort imports with isort

  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        name: Autoformat with black
        args: [-t, py38, -l, "100"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: requirements-txt-fixer

  - repo: https://github.com/PyCQA/doc8
    rev: 0.8.1rc3
    hooks:
    - id: doc8
      name: Autoformat with doc8
      args: [--max-line-length, "100"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: Linting with flake8
        exclude: docs/conf.py
        additional_dependencies: [flake8-comprehensions, flake8-builtins, flake8-blind-except, flake8-bugbear, flake8-use-fstring, flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        name: Static type checking with mypy
        files: pynhd

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        name: Upgrade synax to python 3.6+ with pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        name: Check for security issues with bandit
        args: [-lll, --recursive, pynhd]
        files: .py$
