repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: check-added-large-files
      args: ['--maxkb=50000']
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: mixed-line-ending
      args: ['--fix=lf']

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
    - id: setup-cfg-fmt
      name: Autoformat setup.cfg
      args: [--min-py3-version, "3.7"]

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.5
    hooks:
    - id: pycln
      name: Find and remove unused import statements
      args: [--config=pyproject.toml]

  - repo: https://github.com/bwhmather/ssort
    rev: v0.11.5
    hooks:
    - id: ssort
      name: Sorting top level statements with ssort

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: Sort imports with isort

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      name: Autoformat with black
      args: [-t, py38, -l, "100"]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    - id: blacken-docs
      name: Autoformat codes in docstrings with blacken-docs
      additional_dependencies: [black]
      args: [-t, py38, -l, "100"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    - id: rst-backticks
      name: Check backsticks in rst files
    - id: rst-directive-colons
      name: Check directives in rst files

  - repo: https://github.com/PyCQA/doc8
    rev: 0.11.1
    hooks:
    - id: doc8
      name: Check documentation formats with doc8
      args: [--max-line-length, "100"]

  # - repo: https://github.com/terrencepreilly/darglint
  #   rev: v1.8.1
  #   hooks:
  #   - id: darglint
  #     name: Lint docstrings with Darglint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    - id: codespell
      name: Checks for common misspellings in text files.

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    - id: pyupgrade
      name: Upgrade synax to python 3.7+ with pyupgrade
      args: [--py37-plus]

  - repo: https://github.com/guilatrova/tryceratops
    rev: v1.0.1
    hooks:
    - id: tryceratops
      name: Check try-exceptions blocks with tryceratops

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      name: Linting with flake8
      additional_dependencies:
      - flake8-comprehensions
      - flake8-builtins
      - flake8-blind-except
      - flake8-bugbear
      - flake8-use-fstring
      - flake8-docstrings
      - flake8-simplify

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    - id: mypy
      name: Static type checking with mypy
      exclude: tests
      files: pygeohydro
      additional_dependencies:
      - types-all
      - git+https://github.com/cheginit/async_retriever.git
      - git+https://github.com/cheginit/pygeoogc.git
      - git+https://github.com/cheginit/pygeoutils.git
      - git+https://github.com/cheginit/pynhd.git

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      name: Check for security issues with bandit
      args: [-lll, --recursive, pygeohydro]
      files: .py$
