repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: Sort imports with isort

  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Autoformat with black
        args: [-t, py38, -l, "100"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: requirements-txt-fixer
    - id: check-added-large-files
      args: ['--maxkb=50000']
    - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.1
    hooks:
    - id: rst-backticks
    - id: rst-directive-colons

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
    - id: shfmt

  - repo: https://github.com/PyCQA/doc8
    rev: 0.9.0a1
    hooks:
    - id: doc8
      name: Autoformat with doc8
      args: [--max-line-length, "100"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        name: Linting with flake8
        exclude: docs/conf.py
        additional_dependencies: [flake8-comprehensions, flake8-builtins, flake8-blind-except, flake8-bugbear, flake8-use-fstring, flake8-docstrings, flake8-simplify]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        name: Static type checking with mypy
        exclude: tests
        files: hydrodata

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
      - id: pyupgrade
        name: Upgrade synax to python 3.6+ with pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        name: Check for security issues with bandit
        args: [-lll, --recursive, hydrodata]
        files: .py$

  - repo: https://github.com/nbQA-dev/nbQA
    rev: v0.5.8-2-g007eb3cf60194030c5b4cf133beeada5009badfb
    hooks:
      - id: nbqa-isort
        name: Format notebooks; sort imports by isort
        files: docs/examples
        args: [--nbqa-mutate]

      - id: nbqa-black
        name: Format notebooks; reformat by black
        files: docs/examples
        args: [--nbqa-mutate]

      - id: nbqa-pyupgrade
        files: docs/examples
        name: Format notebooks; upgrade syntax to Python 3.6+ by pyupgrade
        args: [--nbqa-mutate]
