name: hydrodata-binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - setuptools
  - owslib
  - pyproj
  - defusedxml
  - requests
  - aiohttp
  - chardet
  - aiodns
  - brotlipy
  - nest-asyncio
  - xarray
  - netCDF4
  - geopandas
  - pyarrow
  - openpyxl
  - rasterio
  - shapely
  - orjson
  - simplejson
  - lxml
  - dask
  - networkx
  - matplotlib-base
  - folium
  - hydrodata

  # xarray speedups
  - bottleneck

  # dep for plotting with geopandas
  - descartes
  - cartopy
  - cmocean
  - mapclassify

  # third-party deps for the examples
  - osmnx
