name: hydrodata
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - owslib
  - scipy
  - pandas
  - numba
  - matplotlib
  - descartes
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - lxml
  - geopandas
  - folium
  - rasterio
  - pyproj
  - proj
  - gdal
  - networkx
  - geojson
  - simplejson
  - pytables
  - pip:
    - pqdm
    - arcgis2geojson
