name: hydrodata
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - owslib
  - scipy
  - pandas
  - numba
  - matplotlib
  - descartes
  - xarray
  - cartopy
  - dask
  - netCDF4
  - bottleneck
  - lxml
  - geopandas
  - folium
  - jupyterlab
  - pyproj
  - proj
  - gdal
  - pip:
    - networkx
    - pqdm
    - arcgis2geojson
    - bump2version
    - wheel
    - watchdog
    - flake8
    - sphinx
    - sphinx-material
    - sphinx-copybutton
    - nbsphinx
    - twine
    - tox
    - coverage
    - pytest-runner
    - pytest-cov
    - pytest-xdist
    - codecov
    - numpydoc
    - mypy==0.761
    - pre-commit
    - geojson
    - black
    - rasterstats
    - tables
    - xlrd
    - pqdm
    - recommonmark
    -sphinx-markdown-tables
