name: hyd
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - owslib
  - scipy
  - pandas
  - pyarrow
  - numba
  - matplotlib
  - descartes
  - xarray
  - cartopy
  - dask
  - netCDF4
  - bottleneck
  - lxml
  - geopandas
  - folium
  - rasterio
  - jupyterlab
  - ipywidgets
  - pyproj
  - proj
  - gdal
  - networkx
  - geojson
  - simplejson
  - pytables
  - flake8
  - flake8-comprehensions
  - flake8-rst
  - pycodestyle
  - sphinx
  - nbsphinx
  - twine
  - tox
  - coverage
  - mypy
  - pre-commit
  - pytest-runner
  - pytest-cov
  - pytest-xdist
  - codecov
  - numpydoc
  - black
  - sphinx-copybutton
  - recommonmark
  - wheel
  - watchdog
  - pandas-vet
  - pip:
    - pqdm
    - arcgis2geojson
    - bump2version
    - sphinx-material
