name: hydrodata-binder
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - hydrodata

  # xarray speedups
  - bottleneck

  # dep for plotting with geopandas
  - descartes
  - cartopy
  - cmocean
  - mapclassify

  # third-party deps for the examples
  - osmnx

