name: hydrodata-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - setuptools
  - owslib
  - pyproj
  - defusedxml
  - requests
  - aiohttp
  - chardet
  - aiodns
  - brotlipy
  - nest-asyncio
  - xarray
  - netCDF4
  - geopandas
  - pyarrow
  - openpyxl
  - rasterio
  - shapely
  - orjson
  - simplejson
  - lxml
  - dask
  - networkx
  - matplotlib-base
  - folium

  - setuptools_scm
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - codecov
  - coverage

  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - recommonmark
  - nbsphinx
  - sphinx
  - sphinx-copybutton
  - numpydoc

  - beautifulsoup4
  - python-slugify
  - css-html-js-minify
  - unidecode
  - pip
  - pip:
    - numbagg
    - nbsphinx_link
    - sphinx-inline-tabs
    - git+https://github.com/bashtage/sphinx-material.git
    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
    - git+https://github.com/cheginit/pynhd.git
    - git+https://github.com/cheginit/py3dep.git
    - git+https://github.com/cheginit/pydaymet.git
