name: hydrodata-docs
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - sphinx
  - pip:
      - geopandas
      - rasterio
      - geojson
      - simplejson
      - pqdm
      - arcgis2geojson
      - folium
      - nbsphinx
      - netCDF4
      - bottleneck
      - lxml
      - xlrd
      - tables
      - owslib
      - scipy
      - pandas
      - numba
      - matplotlib
      - descartes
      - xarray
      - dask
      - networkx
      - numpydoc
      - ipykernel
      - ipython
      - sphinx-markdown-tables
      - sphinx-material
      - sphinx-copybutton
      - recommonmark
