name: hydrodata-docs
channels:
  - anaconda
dependencies:
  - python=3.7
  - pip
  - cartopy
  - pip:
      - geopandas
      - geojson
      - rasterstats
      - sphinx
      - sphinx_rtd_theme
      - sphinx-copybutton
      - nbsphinx
      - netCDF4
      - bottleneck
      - lxml
      - owslib
      - scipy
      - pandas
      - matplotlib
      - descartes
      - xarray
      - numpydoc
      - ipykernel
      - ipython
      - mock
      - pycurl
